name: darwin-x64

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ linux-x64 ]
    types:
      - completed

jobs:
  darwin-x64-python3:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'alchitry/oss-cad-suite-build'
      - name: Cache sources
        id: cache-sources
        uses: actions/cache@v4
        with:
          path: _sources
          key: cache-sources-python3
      - name: Download previous build
        run: |
          URL="https://github.com/alchitry/oss-cad-suite-build/releases/download/bucket-darwin-x64/darwin-x64-python3.tgz"
          if wget --spider "${URL}" 2>/dev/null; then
              wget -qO- "${URL}" --retry-connrefused --read-timeout=20 --timeout=15 --retry-on-http-error=404 | tar xvfz -
          else
              echo "Previous version not found in bucket"
          fi
      - name: Download linux-x64-python3-native
        run: wget -qO- "https://github.com/alchitry/oss-cad-suite-build/releases/download/bucket-linux-x64/linux-x64-python3-native.tgz" --retry-connrefused --read-timeout=20 --timeout=15 --retry-on-http-error=404 | tar xvfz -
      - name: Build
        run: ./builder.py build --arch=darwin-x64 --target=python3 --single --tar
      - uses: ncipollo/release-action@v1
        if: hashFiles('darwin-x64-python3.tgz') != ''
        with:
          allowUpdates: True
          prerelease: True
          omitBody: True
          omitBodyDuringUpdate: True
          omitNameDuringUpdate: True
          tag: bucket-darwin-x64
          artifacts: "darwin-x64-python3.tgz"
          token: ${{ secrets.GITHUB_TOKEN }}
  darwin-x64-xdot:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: darwin-x64-python3
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'alchitry/oss-cad-suite-build'
      - name: Cache sources
        id: cache-sources
        uses: actions/cache@v4
        with:
          path: _sources
          key: cache-sources-xdot
      - name: Download previous build
        run: |
          URL="https://github.com/alchitry/oss-cad-suite-build/releases/download/bucket-darwin-x64/darwin-x64-xdot.tgz"
          if wget --spider "${URL}" 2>/dev/null; then
              wget -qO- "${URL}" --retry-connrefused --read-timeout=20 --timeout=15 --retry-on-http-error=404 | tar xvfz -
          else
              echo "Previous version not found in bucket"
          fi
      - name: Download darwin-x64-python3
        run: wget -qO- "https://github.com/alchitry/oss-cad-suite-build/releases/download/bucket-darwin-x64/darwin-x64-python3.tgz" --retry-connrefused --read-timeout=20 --timeout=15 --retry-on-http-error=404 | tar xvfz -
      - name: Download linux-x64-python3-native
        run: wget -qO- "https://github.com/alchitry/oss-cad-suite-build/releases/download/bucket-linux-x64/linux-x64-python3-native.tgz" --retry-connrefused --read-timeout=20 --timeout=15 --retry-on-http-error=404 | tar xvfz -
      - name: Build
        run: ./builder.py build --arch=darwin-x64 --target=xdot --single --tar
      - uses: ncipollo/release-action@v1
        if: hashFiles('darwin-x64-xdot.tgz') != ''
        with:
          allowUpdates: True
          prerelease: True
          omitBody: True
          omitBodyDuringUpdate: True
          omitNameDuringUpdate: True
          tag: bucket-darwin-x64
          artifacts: "darwin-x64-xdot.tgz"
          token: ${{ secrets.GITHUB_TOKEN }}
  darwin-x64-graphviz:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'alchitry/oss-cad-suite-build'
      - name: Cache sources
        id: cache-sources
        uses: actions/cache@v4
        with:
          path: _sources
          key: cache-sources-graphviz
      - name: Download previous build
        run: |
          URL="https://github.com/alchitry/oss-cad-suite-build/releases/download/bucket-darwin-x64/darwin-x64-graphviz.tgz"
          if wget --spider "${URL}" 2>/dev/null; then
              wget -qO- "${URL}" --retry-connrefused --read-timeout=20 --timeout=15 --retry-on-http-error=404 | tar xvfz -
          else
              echo "Previous version not found in bucket"
          fi
      - name: Build
        run: ./builder.py build --arch=darwin-x64 --target=graphviz --single --tar
      - uses: ncipollo/release-action@v1
        if: hashFiles('darwin-x64-graphviz.tgz') != ''
        with:
          allowUpdates: True
          prerelease: True
          omitBody: True
          omitBodyDuringUpdate: True
          omitNameDuringUpdate: True
          tag: bucket-darwin-x64
          artifacts: "darwin-x64-graphviz.tgz"
          token: ${{ secrets.GITHUB_TOKEN }}
  darwin-x64-yosys:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'alchitry/oss-cad-suite-build'
      - name: Cache sources
        id: cache-sources
        uses: actions/cache@v4
        with:
          path: _sources
          key: cache-sources-yosys
      - name: Download previous build
        run: |
          URL="https://github.com/alchitry/oss-cad-suite-build/releases/download/bucket-darwin-x64/darwin-x64-yosys.tgz"
          if wget --spider "${URL}" 2>/dev/null; then
              wget -qO- "${URL}" --retry-connrefused --read-timeout=20 --timeout=15 --retry-on-http-error=404 | tar xvfz -
          else
              echo "Previous version not found in bucket"
          fi
      - name: Download linux-x64-abc
        run: wget -qO- "https://github.com/alchitry/oss-cad-suite-build/releases/download/bucket-linux-x64/linux-x64-abc.tgz" --retry-connrefused --read-timeout=20 --timeout=15 --retry-on-http-error=404 | tar xvfz -
      - name: Build
        run: ./builder.py build --arch=darwin-x64 --target=yosys --single --tar
      - uses: ncipollo/release-action@v1
        if: hashFiles('darwin-x64-yosys.tgz') != ''
        with:
          allowUpdates: True
          prerelease: True
          omitBody: True
          omitBodyDuringUpdate: True
          omitNameDuringUpdate: True
          tag: bucket-darwin-x64
          artifacts: "darwin-x64-yosys.tgz"
          token: ${{ secrets.GITHUB_TOKEN }}
  darwin-x64-nextpnr-ice40:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: darwin-x64-python3
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'alchitry/oss-cad-suite-build'
      - name: Cache sources
        id: cache-sources
        uses: actions/cache@v4
        with:
          path: _sources
          key: cache-sources-nextpnr-ice40
      - name: Download previous build
        run: |
          URL="https://github.com/alchitry/oss-cad-suite-build/releases/download/bucket-darwin-x64/darwin-x64-nextpnr-ice40.tgz"
          if wget --spider "${URL}" 2>/dev/null; then
              wget -qO- "${URL}" --retry-connrefused --read-timeout=20 --timeout=15 --retry-on-http-error=404 | tar xvfz -
          else
              echo "Previous version not found in bucket"
          fi
      - name: Download darwin-x64-python3
        run: wget -qO- "https://github.com/alchitry/oss-cad-suite-build/releases/download/bucket-darwin-x64/darwin-x64-python3.tgz" --retry-connrefused --read-timeout=20 --timeout=15 --retry-on-http-error=404 | tar xvfz -
      - name: Download linux-x64-icestorm-bba
        run: wget -qO- "https://github.com/alchitry/oss-cad-suite-build/releases/download/bucket-linux-x64/linux-x64-icestorm-bba.tgz" --retry-connrefused --read-timeout=20 --timeout=15 --retry-on-http-error=404 | tar xvfz -
      - name: Download linux-x64-nextpnr-bba
        run: wget -qO- "https://github.com/alchitry/oss-cad-suite-build/releases/download/bucket-linux-x64/linux-x64-nextpnr-bba.tgz" --retry-connrefused --read-timeout=20 --timeout=15 --retry-on-http-error=404 | tar xvfz -
      - name: Download linux-x64-python3-native
        run: wget -qO- "https://github.com/alchitry/oss-cad-suite-build/releases/download/bucket-linux-x64/linux-x64-python3-native.tgz" --retry-connrefused --read-timeout=20 --timeout=15 --retry-on-http-error=404 | tar xvfz -
      - name: Build
        run: ./builder.py build --arch=darwin-x64 --target=nextpnr-ice40 --single --tar
      - uses: ncipollo/release-action@v1
        if: hashFiles('darwin-x64-nextpnr-ice40.tgz') != ''
        with:
          allowUpdates: True
          prerelease: True
          omitBody: True
          omitBodyDuringUpdate: True
          omitNameDuringUpdate: True
          tag: bucket-darwin-x64
          artifacts: "darwin-x64-nextpnr-ice40.tgz"
          token: ${{ secrets.GITHUB_TOKEN }}
  darwin-x64-icestorm:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'alchitry/oss-cad-suite-build'
      - name: Cache sources
        id: cache-sources
        uses: actions/cache@v4
        with:
          path: _sources
          key: cache-sources-icestorm
      - name: Download previous build
        run: |
          URL="https://github.com/alchitry/oss-cad-suite-build/releases/download/bucket-darwin-x64/darwin-x64-icestorm.tgz"
          if wget --spider "${URL}" 2>/dev/null; then
              wget -qO- "${URL}" --retry-connrefused --read-timeout=20 --timeout=15 --retry-on-http-error=404 | tar xvfz -
          else
              echo "Previous version not found in bucket"
          fi
      - name: Build
        run: ./builder.py build --arch=darwin-x64 --target=icestorm --single --tar
      - uses: ncipollo/release-action@v1
        if: hashFiles('darwin-x64-icestorm.tgz') != ''
        with:
          allowUpdates: True
          prerelease: True
          omitBody: True
          omitBodyDuringUpdate: True
          omitNameDuringUpdate: True
          tag: bucket-darwin-x64
          artifacts: "darwin-x64-icestorm.tgz"
          token: ${{ secrets.GITHUB_TOKEN }}
  darwin-x64-system-resources-min:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'alchitry/oss-cad-suite-build'
      - name: Cache sources
        id: cache-sources
        uses: actions/cache@v4
        with:
          path: _sources
          key: cache-sources-system-resources-min
      - name: Download previous build
        run: |
          URL="https://github.com/alchitry/oss-cad-suite-build/releases/download/bucket-darwin-x64/darwin-x64-system-resources-min.tgz"
          if wget --spider "${URL}" 2>/dev/null; then
              wget -qO- "${URL}" --retry-connrefused --read-timeout=20 --timeout=15 --retry-on-http-error=404 | tar xvfz -
          else
              echo "Previous version not found in bucket"
          fi
      - name: Build
        run: ./builder.py build --arch=darwin-x64 --target=system-resources-min --single --tar
      - uses: ncipollo/release-action@v1
        if: hashFiles('darwin-x64-system-resources-min.tgz') != ''
        with:
          allowUpdates: True
          prerelease: True
          omitBody: True
          omitBodyDuringUpdate: True
          omitNameDuringUpdate: True
          tag: bucket-darwin-x64
          artifacts: "darwin-x64-system-resources-min.tgz"
          token: ${{ secrets.GITHUB_TOKEN }}
  darwin-x64-alchitry-labs:
    runs-on: ubuntu-latest
    needs: [ darwin-x64-graphviz, darwin-x64-icestorm, darwin-x64-nextpnr-ice40, darwin-x64-python3, darwin-x64-system-resources-min, darwin-x64-xdot, darwin-x64-yosys ]
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
        with:
          repository: 'alchitry/oss-cad-suite-build'
      - name: Download darwin-x64-graphviz
        run: wget -qO- "https://github.com/alchitry/oss-cad-suite-build/releases/download/bucket-darwin-x64/darwin-x64-graphviz.tgz" --retry-connrefused --read-timeout=20 --timeout=15 --retry-on-http-error=404 | tar xvfz -
      - name: Download darwin-x64-icestorm
        run: wget -qO- "https://github.com/alchitry/oss-cad-suite-build/releases/download/bucket-darwin-x64/darwin-x64-icestorm.tgz" --retry-connrefused --read-timeout=20 --timeout=15 --retry-on-http-error=404 | tar xvfz -
      - name: Download darwin-x64-nextpnr-ice40
        run: wget -qO- "https://github.com/alchitry/oss-cad-suite-build/releases/download/bucket-darwin-x64/darwin-x64-nextpnr-ice40.tgz" --retry-connrefused --read-timeout=20 --timeout=15 --retry-on-http-error=404 | tar xvfz -
      - name: Download darwin-x64-python3
        run: wget -qO- "https://github.com/alchitry/oss-cad-suite-build/releases/download/bucket-darwin-x64/darwin-x64-python3.tgz" --retry-connrefused --read-timeout=20 --timeout=15 --retry-on-http-error=404 | tar xvfz -
      - name: Download darwin-x64-system-resources-min
        run: wget -qO- "https://github.com/alchitry/oss-cad-suite-build/releases/download/bucket-darwin-x64/darwin-x64-system-resources-min.tgz" --retry-connrefused --read-timeout=20 --timeout=15 --retry-on-http-error=404 | tar xvfz -
      - name: Download darwin-x64-xdot
        run: wget -qO- "https://github.com/alchitry/oss-cad-suite-build/releases/download/bucket-darwin-x64/darwin-x64-xdot.tgz" --retry-connrefused --read-timeout=20 --timeout=15 --retry-on-http-error=404 | tar xvfz -
      - name: Download darwin-x64-yosys
        run: wget -qO- "https://github.com/alchitry/oss-cad-suite-build/releases/download/bucket-darwin-x64/darwin-x64-yosys.tgz" --retry-connrefused --read-timeout=20 --timeout=15 --retry-on-http-error=404 | tar xvfz -
      - name: Build
        run: ./builder.py build --arch=darwin-x64 --target=alchitry-labs --single
      - uses: ncipollo/release-action@v1
        if: hashFiles('_outputs/darwin-x64/alchitry-labs/*.tgz') != ''
        with:
          allowUpdates: True
          omitBody: True
          omitBodyDuringUpdate: True
          omitNameDuringUpdate: True
          tag: ${{ steps.date.outputs.date }}
          artifacts: "_outputs/darwin-x64/alchitry-labs/*.tgz"
          token: ${{ secrets.GITHUB_TOKEN }}
